apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "badevand-exporter.fullname" . }}
  labels:
    {{- include "badevand-exporter.labels" . | nindent 4 }}
data:
  config.yaml: |
    sites:
    {{- toYaml .Values.config.sites | nindent 6 }}
    include: {{ .Values.config.include | quote }}
    exclude: {{ .Values.config.exclude | quote }}
    interval: {{ .Values.config.interval | quote }}
    badevand_api_key: {{ .Values.config.badevandApiKey | quote }}
    port: 8080
